services:
  db:
    profiles:
      - db

  migrate:
    profiles:
      - migrate

  redis:
    profiles:
      - db

  redis-rest:
    profiles:
      - db

  stripe-listener:
    profiles:
      - app_pre_async

  stripe-webhook-check:
    profiles:
      - app_post_check
