"""
Generate DPO training pairs: (winner, loser)

- Winner: Real 10-move puzzles from training data
- Loser: Short-path puzzles generated by the model using same start/goal

This script:
1. Loads a pretrained checkpoint
2. For each training sample (winner), generates a puzzle with the model
3. If the generated puzzle has fewer moves (loser), save the pair
4. Output: JSONL with {"winner": {...}, "loser": {...}} pairs

Usage:
    python generate_dpo_data.py \
        --checkpoint output_v2_clean/best_model.pt \
        --train-data ../data/train-10move-300k-shuf.jsonl \
        --output dpo_pairs.jsonl \
        --num-samples 50000
"""

import argparse
import hashlib
import json
from pathlib import Path
from tqdm import tqdm

import torch

from model_v2 import PuzzleGeneratorV2, config_for_preset


# Tile ID remapping
TILE_REMAP = {0: 0, 1: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6}
TILE_REMAP_INV = {v: k for k, v in TILE_REMAP.items()}


def remap_tile(tile_id: int) -> int:
    return TILE_REMAP.get(tile_id, 2)


def remap_tile_inv(idx: int) -> int:
    return TILE_REMAP_INV.get(idx, 4)


def try_import_verifier():
    try:
        from mazle_eval import validate_ice_interior
        return validate_ice_interior
    except ImportError:
        return None


def validate_puzzle(tiles, start_x, start_y, goal_x, goal_y, validate_fn, target_moves=10):
    """Validate a puzzle and return the result."""
    H, W = 13, 13
    grid = []
    flat = tiles.tolist() if hasattr(tiles, 'tolist') else tiles
    for y in range(H):
        row = []
        for x in range(W):
            idx = flat[y * W + x]
            row.append(remap_tile_inv(idx))
        grid.append(row)

    return validate_fn(grid, start_x, start_y, goal_x, goal_y, target_moves)


def tiles_to_interior(tiles_flat):
    """Convert flat remapped tiles to tilesInterior format."""
    H, W = 13, 13
    grid = []
    flat = tiles_flat.tolist() if hasattr(tiles_flat, 'tolist') else tiles_flat
    for y in range(H):
        row = []
        for x in range(W):
            idx = flat[y * W + x]
            row.append(remap_tile_inv(idx))
        grid.append(row)
    return grid


def main():
    parser = argparse.ArgumentParser(description="Generate DPO training pairs")
    parser.add_argument("--checkpoint", type=str, required=True, help="Path to pretrained checkpoint")
    parser.add_argument("--train-data", type=str, required=True, help="Path to training JSONL (winners)")
    parser.add_argument("--output", type=str, required=True, help="Output path for DPO pairs JSONL")
    parser.add_argument("--num-samples", type=int, default=50000, help="Number of pairs to generate")
    parser.add_argument("--preset", type=str, default="base", choices=["small", "base", "large"])
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--min-move-diff", type=int, default=2, help="Minimum move difference for loser (loser must be at least this many moves shorter)")
    parser.add_argument("--max-loser-moves", type=int, default=7, help="Maximum moves for loser (to ensure it's clearly 'bad')")
    args = parser.parse_args()

    # Device
    if torch.cuda.is_available():
        device = torch.device("cuda")
    elif torch.backends.mps.is_available():
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
    print(f"Device: {device}")

    # Verifier
    validate_fn = try_import_verifier()
    if not validate_fn:
        raise RuntimeError("Rust verifier required for DPO data generation")
    print("Rust verifier loaded")

    # Load model
    config = config_for_preset(args.preset)
    model = PuzzleGeneratorV2(config).to(device)

    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    # Prefer EMA weights if available
    if "ema_shadow" in ckpt:
        model.load_state_dict(ckpt["ema_shadow"], strict=False)
        print(f"Loaded EMA weights from: {args.checkpoint}")
    else:
        model.load_state_dict(ckpt["model_state"])
        print(f"Loaded checkpoint: {args.checkpoint}")
    model.eval()

    # Load training data
    train_samples = []
    with open(args.train_data) as f:
        for line in f:
            train_samples.append(json.loads(line))
    print(f"Loaded {len(train_samples)} training samples")

    # Generate pairs
    pairs = []
    stats = {
        "attempted": 0,
        "model_not_solvable": 0,
        "model_too_many_moves": 0,
        "model_too_few_moves_diff": 0,
        "valid_pairs": 0,
    }

    with torch.no_grad():
        pbar = tqdm(train_samples[:args.num_samples * 3], desc="Generating pairs")  # Process 3x to account for filtering

        for i, winner in enumerate(pbar):
            if len(pairs) >= args.num_samples:
                break

            stats["attempted"] += 1

            # Get winner info
            winner_start = winner["start"]
            winner_goal = winner["goal"]
            winner_optimal = winner.get("optimal_moves", 10)

            # Skip if winner isn't exactly 10 moves
            if winner_optimal != 10:
                continue

            # Convert winner start/goal to flat positions
            W = 13
            start_pos = winner_start["y"] * W + winner_start["x"]
            goal_pos = winner_goal["y"] * W + winner_goal["x"]

            # Generate puzzle with model using deterministic seed
            seed = f"dpo-{i}"
            seed_int = int(hashlib.sha256(seed.encode()).hexdigest()[:16], 16)
            gen = torch.Generator(device=device)
            gen.manual_seed(seed_int)

            # Initialize with all MASK tokens
            x_t = torch.full((1, 169), model.mask_token_id, dtype=torch.long, device=device)

            # We use the SAME start/goal as the winner, not model-predicted positions
            # This is important: we want to compare tiles, not positions
            start_pos_t = torch.tensor([start_pos], dtype=torch.long, device=device)
            goal_pos_t = torch.tensor([goal_pos], dtype=torch.long, device=device)

            # Iterative denoising
            for step in reversed(range(model.num_timesteps)):
                t = torch.tensor([step], dtype=torch.long, device=device)

                # Forward pass with fixed start/goal
                outputs = model(x_t, t, start_pos_t, goal_pos_t)
                logits = outputs["tile_logits"]  # (1, 169, vocab_size)
                logits = logits / args.temperature

                # Sample tiles using Gumbel-max
                gumbel_noise = torch.rand(logits.shape, device=device, generator=gen)
                gumbel = -torch.log(-torch.log(gumbel_noise.clamp(min=1e-10)))
                sampled = (logits + gumbel).argmax(dim=-1)  # (1, 169)

                if step > 0:
                    mask_prob_t = 1.0 - model.alpha_bar[step]
                    mask_prob_prev = 1.0 - model.alpha_bar[step - 1]
                    keep_mask_prob = mask_prob_prev / mask_prob_t.clamp(min=1e-8)

                    rand_vals = torch.rand((1, 169), device=device, generator=gen)
                    keep_mask = rand_vals < keep_mask_prob
                    currently_masked = x_t == model.mask_token_id
                    x_t = torch.where(currently_masked & keep_mask, model.mask_token_id, sampled)
                else:
                    x_t = sampled

            # Validate generated puzzle
            loser_tiles_flat = x_t[0].cpu()
            sx, sy = winner_start["x"], winner_start["y"]
            gx, gy = winner_goal["x"], winner_goal["y"]

            vr = validate_puzzle(loser_tiles_flat, sx, sy, gx, gy, validate_fn)

            if not vr.solvable:
                stats["model_not_solvable"] += 1
                continue

            loser_moves = vr.optimal_moves

            # Check if loser is clearly worse (shorter path)
            if loser_moves > args.max_loser_moves:
                stats["model_too_many_moves"] += 1
                continue

            if (winner_optimal - loser_moves) < args.min_move_diff:
                stats["model_too_few_moves_diff"] += 1
                continue

            # Valid pair found!
            stats["valid_pairs"] += 1

            # Build loser dict matching winner format
            loser = {
                "tilesInterior": tiles_to_interior(loser_tiles_flat),
                "start": winner_start,
                "goal": winner_goal,
                "optimal_moves": loser_moves,
            }

            pairs.append({
                "winner": winner,
                "loser": loser,
            })

            pbar.set_postfix(pairs=len(pairs), valid_rate=f"{stats['valid_pairs']/stats['attempted']:.1%}")

    # Save pairs
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        for pair in pairs:
            f.write(json.dumps(pair) + "\n")

    print(f"\nGeneration complete!")
    print(f"Stats: {json.dumps(stats, indent=2)}")
    print(f"Saved {len(pairs)} pairs to {output_path}")

    # Print sample pair
    if pairs:
        sample = pairs[0]
        print(f"\nSample pair:")
        print(f"  Winner: {sample['winner']['optimal_moves']} moves")
        print(f"  Loser:  {sample['loser']['optimal_moves']} moves")


if __name__ == "__main__":
    main()
