# override.compose.yaml for mazle-generator
# Activates the profiles for the Rust app services

services:
  rust-app:
    build:
      target: runner
    profiles:
      - app

  rust-app-health-check:
    profiles:
      - app_post_check
